---
title: "class3_補充"
author: "york"
date: "2018/5/9"
output: html_document
editor_options: 
  chunk_output_type: console
---

###繪製基本圖形
- plot	繪製基本圖(畫布)

###增添額外資訊
- lines	把資料點用線連接
- points	繪製新的資料點
- text	補充文字說明在圖上
- title	補充主旨
- mtext	在圖外顯示大主旨
- axis	增加軸的labels

###plot type
```{r}
x <- 1:6
y <- x
par(mfrow=c(2,4))
types <- c('p','l', 'o', 'b', 'c', 's', 'h', 'n')
for(t in types){
  #print(t)
  title <- paste('type:', t)
  plot(x,y, type = t, main = title)
}

```


### plot example
```{r}
data(iris)
str(iris)
plot(iris$Petal.Length,iris$Petal.Width,type='n',yaxt='n')
points(iris$Petal.Length,iris$Petal.Width,col=iris$Species)
abline(h=0.9,col='grey',lty = 2)
abline(v=2.5,col='grey',lty = 2)
legend(4.5,1,pch=1,legend = levels(iris$Species),col=1:3)
text(iris$Petal.Length+0.1,iris$Petal.Width+0.05,1:nrow(iris),cex=0.5)
title("iris")
#text(iris$Petal.Length+0.1,iris$Petal.Width+0.05,paste('(',iris$Petal.Length,', ',iris$Petal.Width,')'),cex=0.5)

#legend('bottomright',pch=1,legend = levels(iris$Species),col=1:3)


```

### mice
```{R}
library(mice)
data(iris)
na_list = sample(1:nrow(iris),15)
iris[na_list,'Sepal.Length'] = NA

mice.data <- mice(iris,m = 3,method = "cart",seed = 1206)

complete(mice.data,1)

```

### connect mysql
```{R}
#Method 1:
#install.packages('RJDBC')
install.packages("rJava",type='source')
library('RJDBC')
jar.loc <- '~/Downloads/mysql-connector-java-5.1.44/mysql-connector-java-5.1.44-bin.jar'
driver <- JDBC("com.mysql.jdbc.Driver",jar.loc,identifier.quote="")

conn <- dbConnect(driver, "jdbc:mysql://localhost:3306/test")
data = dbGetQuery(conn, "SELECT * FROM author")
head(data)

dbDisconnect(conn)

#Method 2:
install.packages('RMySQL')
library('RMySQL')
conn = dbConnect(MySQL(), dbname = "test")
data = dbGetQuery(conn, "select * from author")
head(data)
dbDisconnect(conn)
```