---
title: "R_basic3"
author: "York Lin"
date: "2019年05月16日"
output: html_document
editor_options: 
  chunk_output_type: console
---
###繪製基本圖形
- plot	繪製基本圖(畫布)

###增添額外資訊
- lines	把資料點用線連接
- points	繪製新的資料點
- text	補充文字說明在圖上
- title	補充主旨
- mtext	在圖外顯示大主旨
- axis	增加軸的labels

###plot type
```{r}
x <- 1:6
y <- x
par(mfrow=c(2,4))
types <- c('p','l', 'o', 'b', 'c', 's', 'h', 'n')
for(t in types){
  #print(t)
  title <- paste('type:', t)
  plot(x,y, type = t, main = title)
}

```

### plot example
```{r}
data(iris)
str(iris)
plot(iris$Petal.Length,iris$Petal.Width,type='n')
points(iris$Petal.Length,iris$Petal.Width,col=iris$Species)
abline(h=0.9,col='grey',lty = 2)
abline(v=2.5,col='grey',lty = 2)
#legend(4.5,1,pch=1,legend = levels(iris$Species),col=1:3)
legend('bottomright',pch=1,legend = levels(iris$Species),col=1:3)
#text(iris$Petal.Length+0.1,iris$Petal.Width+0.05,1:nrow(iris),cex=0.5)
text(iris$Petal.Length+0.1,iris$Petal.Width+0.05,paste('(',iris$Petal.Length,', ',iris$Petal.Width,')'),cex=0.5)

title("iris")


```